export type Question = {
  id: string;
  text: string;
  options: string[];
  answerIndex: number;
  explanation?: string;
};

// NHPC License Exam Questions (from nhpcQS.pdf)
const baseQuestions: Question[] = [
  // Anatomy & Physiology (1–10)
  { id: 'q1', text: 'How many bones are present in an adult human skeleton?', options: ['205', '206', '208', '210'], answerIndex: 1 },
  { id: 'q2', text: 'Which bone forms the helmet-like protection for the brain?', options: ['Mandible', 'Cranium', 'Clavicle', 'Scapula'], answerIndex: 1 },
  { id: 'q3', text: 'The largest organ in the integumentary system is:', options: ['Liver', 'Skin', 'Heart', 'Brain'], answerIndex: 1 },
  { id: 'q4', text: 'The primary function of the muscular system is:', options: ['Protection', 'Movement', 'Hormone production', 'Blood filtration'], answerIndex: 1 },
  { id: 'q5', text: 'Which part of the brain controls balance and coordination?', options: ['Cerebrum', 'Cerebellum', 'Medulla oblongata', 'Hypothalamus'], answerIndex: 1 },
  { id: 'q6', text: 'The normal adult respiratory rate is approximately:', options: ['8–12 breaths/min', '12–20 breaths/min', '20–30 breaths/min', '30–40 breaths/min'], answerIndex: 1 },
  { id: 'q7', text: 'The pacemaker of the heart is:', options: ['AV node', 'SA node', 'Bundle of His', 'Purkinje fibers'], answerIndex: 1 },
  { id: 'q8', text: 'The functional unit of the kidney is:', options: ['Alveolus', 'Nephron', 'Neuron', 'Osteon'], answerIndex: 1 },
  { id: 'q9', text: 'Which vitamin is synthesized by the skin on exposure to sunlight?', options: ['Vitamin A', 'Vitamin B12', 'Vitamin C', 'Vitamin D'], answerIndex: 3 },
  { id: 'q10', text: 'The normal body temperature in Celsius is:', options: ['35.5°C', '36.5–37.5°C', '38–39°C', '39–40°C'], answerIndex: 1 },
  // Community Health (11–35)
  { id: 'q11', text: 'The Alma-Ata Declaration (1978) emphasized:', options: ['Tertiary care', 'Primary Health Care', 'Specialized surgery', 'Advanced diagnostics'], answerIndex: 1 },
  { id: 'q12', text: 'Which is a component of Primary Health Care (PHC)?', options: ['Immunization', 'Open heart surgery', 'CT scan', 'Organ transplant'], answerIndex: 0 },
  { id: 'q13', text: 'The Expanded Program on Immunization (EPI) in Nepal includes vaccine against:', options: ['Measles, Rubella, Japanese Encephalitis', 'All of the above', 'Only polio', 'Only tuberculosis'], answerIndex: 1 },
  { id: 'q14', text: 'The most common mode of transmission of tuberculosis is:', options: ['Droplet', 'Fomite', 'Vector', 'Food-borne'], answerIndex: 0 },
  { id: 'q15', text: 'Which is a preventable risk factor for non-communicable diseases?', options: ['Tobacco use', 'Genetic mutation', 'Congenital defect', 'Aging'], answerIndex: 0 },
  { id: 'q16', text: 'Community diagnosis is primarily based on:', options: ['Hospital records only', 'Survey and data collection in community', "Doctor's opinion", 'Media reports'], answerIndex: 1 },
  { id: 'q17', text: 'The Safe Motherhood Program focuses on reducing:', options: ['Maternal mortality', 'Infant mortality only', 'Child malnutrition', 'Adolescent pregnancy only'], answerIndex: 0 },
  { id: 'q18', text: 'Vitamin A supplementation is routinely given to children to prevent:', options: ['Night blindness', 'Scurvy', 'Rickets', 'Beriberi'], answerIndex: 0 },
  { id: 'q19', text: 'The National Immunization Schedule in Nepal includes BCG at:', options: ['Birth', '6 weeks', '9 months', '1 year'], answerIndex: 0 },
  { id: 'q20', text: 'Which is an indicator of environmental health?', options: ['Access to safe drinking water', 'Number of hospitals', 'Doctor-patient ratio', 'Literacy rate'], answerIndex: 0 },
  { id: 'q21', text: 'Health education uses the principle of:', options: ['Learning by doing', 'Ignoring community beliefs', 'Only lecture method', 'Forcing behaviour change'], answerIndex: 0 },
  { id: 'q22', text: 'The focus of family planning in Nepal is to promote:', options: ['Spacing and limiting births', 'Unlimited children', 'Only female sterilization', 'Abortion only'], answerIndex: 0 },
  { id: 'q23', text: 'Which disease is targeted under the Neglected Tropical Diseases program in Nepal?', options: ['Lymphatic filariasis', 'Malaria only', 'Dengue', 'HIV'], answerIndex: 0 },
  { id: 'q24', text: 'The Millennium Development Goals were replaced by:', options: ['Sustainable Development Goals (SDGs)', 'Alma-Ata goals', 'WHO 2000 goals', 'National Health Policy'], answerIndex: 0 },
  { id: 'q25', text: 'ORS is used primarily for:', options: ['Dehydration due to diarrhea', 'Fever', 'Cough', 'Headache'], answerIndex: 0 },
  { id: 'q26', text: 'The cold chain is maintained for:', options: ['Vaccines', 'Antibiotics', 'Surgery instruments', 'X-ray films'], answerIndex: 0 },
  { id: 'q27', text: 'Which is a vector-borne disease common in Nepal Terai?', options: ['Kala-azar', 'Typhoid', 'Cholera', 'Pneumonia'], answerIndex: 0 },
  { id: 'q28', text: 'Health post in Nepal provides services up to:', options: ['Primary level', 'Secondary level', 'Tertiary level', 'Specialized care'], answerIndex: 0 },
  { id: 'q29', text: 'Nutrition rehabilitation is important in children with:', options: ['Severe acute malnutrition (SAM)', 'Obesity only', 'Normal weight', 'Tall stature'], answerIndex: 0 },
  { id: 'q30', text: 'The purpose of growth monitoring is to detect:', options: ['Malnutrition early', 'Intelligence', 'Sports talent', 'Voice quality'], answerIndex: 0 },
  { id: 'q31', text: 'Which program distributes iron tablets to pregnant women?', options: ['Safe Motherhood', 'EPI', 'TB control', 'Malaria control'], answerIndex: 0 },
  { id: 'q32', text: 'Community participation is key in:', options: ['Primary Health Care', 'Hospital management', 'Medical research', 'Drug manufacturing'], answerIndex: 0 },
  { id: 'q33', text: 'The leading cause of under-5 mortality in Nepal is:', options: ['Pneumonia and diarrhea', 'Congenital anomalies', 'Road accidents', 'Cancer'], answerIndex: 0 },
  { id: 'q34', text: 'Deworming tablet (Albendazole) is given to children every:', options: ['6 months', 'Year', 'Month', 'Week'], answerIndex: 0 },
  { id: 'q35', text: 'Which is NOT a pillar of PHC?', options: ['Intersectoral coordination', 'Appropriate technology', 'Expensive diagnostics', 'Community involvement'], answerIndex: 2 },
  // General Medicine (36–60)
  { id: 'q36', text: 'The most common symptom of pneumonia in children is:', options: ['Fast breathing', 'Rash', 'Joint pain', 'Abdominal pain'], answerIndex: 0 },
  { id: 'q37', text: 'The drug of choice for vivax malaria is:', options: ['Chloroquine', 'Artemisinin', 'Quinine', 'Doxycycline only'], answerIndex: 0 },
  { id: 'q38', text: "Koplik's spots are pathognomonic of:", options: ['Measles', 'Rubella', 'Chickenpox', 'Mumps'], answerIndex: 0 },
  { id: 'q39', text: 'The triad of diabetes mellitus includes polyuria, polydipsia and:', options: ['Polyphagia', 'Weight gain', 'Hypertension', 'Jaundice'], answerIndex: 0 },
  { id: 'q40', text: 'The most common cause of peptic ulcer is:', options: ['H. pylori', 'Stress', 'Spicy food', 'Alcohol only'], answerIndex: 0 },
  { id: 'q41', text: 'In leprosy, the cardinal sign is:', options: ['Hypopigmented anesthetic patch', 'Fever', 'Cough', 'Diarrhea'], answerIndex: 0 },
  { id: 'q42', text: 'The treatment for scabies is:', options: ['Permethrin cream', 'Albendazole', 'Chloroquine', 'Metronidazole'], answerIndex: 0 },
  { id: 'q43', text: 'Which is a feature of schizophrenia?', options: ['Hallucinations and delusions', 'Fever', 'Jaundice', 'Joint swelling'], answerIndex: 0 },
  { id: 'q44', text: 'Neonatal jaundice appearing within 24 hours is likely due to:', options: ['Hemolytic disease', 'Physiological', 'Breast milk', 'Dehydration'], answerIndex: 0 },
  { id: 'q45', text: 'The drug of choice for typhoid fever is:', options: ['Ceftriaxone', 'Paracetamol', 'Amoxicillin', 'Metronidazole'], answerIndex: 0 },
  { id: 'q46', text: 'Clubbing of fingers is seen in:', options: ['Chronic lung disease', 'Acute asthma', 'Common cold', 'Headache'], answerIndex: 0 },
  { id: 'q47', text: 'The commonest cause of acute diarrhea in children is:', options: ['Rotavirus', 'Salmonella', 'E. coli only', 'Vibrio cholerae'], answerIndex: 0 },
  { id: 'q48', text: 'In asthma, the hallmark is:', options: ['Wheezing', 'Stridor', 'Crackles', 'Pleural rub'], answerIndex: 0 },
  { id: 'q49', text: 'The maintenance fluid requirement for a 10 kg child per day is:', options: ['1000 ml', '1500 ml', '500 ml', '2000 ml'], answerIndex: 0 },
  { id: 'q50', text: 'Which is a sign of dehydration in children?', options: ['Sunken eyes', 'Bulging fontanelle', 'Increased urine output', 'Weight gain'], answerIndex: 0 },
  { id: 'q51', text: 'The incubation period of chickenpox is:', options: ['10–21 days', '2–5 days', '1–3 days', '28 days'], answerIndex: 0 },
  { id: 'q52', text: 'The drug used for worm infestation (ascariasis) is:', options: ['Albendazole', 'Chloroquine', 'Metronidazole', 'Ciprofloxacin'], answerIndex: 0 },
  { id: 'q53', text: 'In pulmonary tuberculosis, sputum is examined by:', options: ['AFB smear', 'Culture only', 'X-ray only', 'Blood test'], answerIndex: 0 },
  { id: 'q54', text: 'The commonest skin infection in children is:', options: ['Impetigo', 'Psoriasis', 'Eczema', 'Vitiligo'], answerIndex: 0 },
  { id: 'q55', text: 'Which is a symptom of depression?', options: ['Loss of interest', 'Mania', 'Hallucinations', 'Delusions only'], answerIndex: 0 },
  { id: 'q56', text: 'The treatment for gonorrhea is:', options: ['Ceftriaxone', 'Penicillin G', 'Tetracycline', 'Albendazole'], answerIndex: 0 },
  { id: 'q57', text: 'In neonatal sepsis, the common organism is:', options: ['Group B Streptococcus', 'E. coli', 'Both A and B', 'Candida'], answerIndex: 2 },
  { id: 'q58', text: 'The sign of meningitis in infants is:', options: ['Bulging fontanelle', 'Sunken fontanelle', 'Normal cry', 'Weight gain'], answerIndex: 0 },
  { id: 'q59', text: 'The drug of choice for amoebiasis is:', options: ['Metronidazole', 'Albendazole', 'Chloroquine', 'Paracetamol'], answerIndex: 0 },
  { id: 'q60', text: 'In hypertension, the target blood pressure for adults is below:', options: ['140/90 mmHg', '160/100 mmHg', '120/80 mmHg', '180/110 mmHg'], answerIndex: 0 },
  // Pharmacology & Pharmacy (61–70)
  { id: 'q61', text: 'The route of administration for insulin is:', options: ['Subcutaneous', 'Oral', 'Intravenous only', 'Topical'], answerIndex: 0 },
  { id: 'q62', text: 'Paracetamol is primarily used as:', options: ['Antipyretic and analgesic', 'Antibiotic', 'Antihistamine', 'Antacid'], answerIndex: 0 },
  { id: 'q63', text: 'The drug contraindicated in peptic ulcer is:', options: ['Aspirin', 'Ranitidine', 'Omeprazole', 'Metronidazole'], answerIndex: 0 },
  { id: 'q64', text: 'Salbutamol is used in:', options: ['Asthma', 'Hypertension', 'Diabetes', 'Malaria'], answerIndex: 0 },
  { id: 'q65', text: 'The antidote for paracetamol poisoning is:', options: ['N-acetylcysteine', 'Atropine', 'Naloxone', 'Vitamin K'], answerIndex: 0 },
  { id: 'q66', text: 'Amoxicillin belongs to which class?', options: ['Penicillin', 'Cephalosporin', 'Macrolide', 'Quinolone'], answerIndex: 0 },
  { id: 'q67', text: 'The common side effect of metronidazole is:', options: ['Metallic taste', 'Rash', 'Hypotension', 'Hypoglycemia'], answerIndex: 0 },
  { id: 'q68', text: 'ORS contains:', options: ['Glucose and electrolytes', 'Only sugar', 'Only salt', 'Antibiotics'], answerIndex: 0 },
  { id: 'q69', text: 'The drug used for hookworm is:', options: ['Albendazole', 'Chloroquine', 'Ceftriaxone', 'Paracetamol'], answerIndex: 0 },
  { id: 'q70', text: 'Zinc supplementation is given in diarrhea to:', options: ['Reduce duration', 'Increase fever', 'Cause vomiting', 'Stop ORS'], answerIndex: 0 },
  // General Surgery (71–95)
  { id: 'q71', text: 'The most common cause of acute abdomen in children is:', options: ['Appendicitis', 'Hernia', 'Intussusception', 'Volvulus'], answerIndex: 0 },
  { id: 'q72', text: 'The sign of acute appendicitis is:', options: ["McBurney's point tenderness", 'Rebound tenderness', 'Both A and B', 'Guarding only'], answerIndex: 2 },
  { id: 'q73', text: 'In burns, the rule of nine is used to estimate:', options: ['Percentage of body surface area', 'Depth of burn', 'Cause of burn', 'Pain level'], answerIndex: 0 },
  { id: 'q74', text: 'The treatment for cellulitis is:', options: ['Antibiotics', 'Surgery', 'Analgesics only', 'Antipyretics'], answerIndex: 0 },
  { id: 'q75', text: 'Hydrocele is collection of fluid in:', options: ['Tunica vaginalis', 'Pericardium', 'Pleura', 'Peritoneum'], answerIndex: 0 },
  { id: 'q76', text: 'The commonest hernia in males is:', options: ['Inguinal', 'Femoral', 'Umbilical', 'Incisional'], answerIndex: 0 },
  { id: 'q77', text: 'Fracture healing is best assessed by:', options: ['X-ray', 'MRI', 'CT scan', 'Ultrasound'], answerIndex: 0 },
  { id: 'q78', text: 'The first aid for fracture is:', options: ['Immobilization', 'Massage', 'Hot fomentation', 'Immediate surgery'], answerIndex: 0 },
  { id: 'q79', text: 'In epistaxis, the common site of bleeding is:', options: ["Little's area", 'Posterior nose', 'Sinuses', 'Pharynx'], answerIndex: 0 },
  { id: 'q80', text: 'The drug used for tetanus prophylaxis is:', options: ['Tetanus toxoid', 'Penicillin', 'Metronidazole', 'Paracetamol'], answerIndex: 0 },
  { id: 'q81', text: 'Abscess is treated by:', options: ['Incision and drainage', 'Antibiotics only', 'Compression', 'Heat'], answerIndex: 0 },
  { id: 'q82', text: 'The sign of peritonitis is:', options: ['Board-like rigidity', 'Soft abdomen', 'Hyperactive bowel sounds', 'No tenderness'], answerIndex: 0 },
  { id: 'q83', text: 'In hemorrhoids, bright red bleeding is seen in:', options: ['Internal hemorrhoids', 'External', 'Fistula', 'Fissure'], answerIndex: 0 },
  { id: 'q84', text: 'The commonest cause of intestinal obstruction in neonates is:', options: ["Hirschsprung's disease", 'Appendicitis', 'Hernia', 'Tumor'], answerIndex: 0 },
  { id: 'q85', text: 'Keloid is excessive:', options: ['Scar tissue', 'Pigmentation', 'Infection', 'Bleeding'], answerIndex: 0 },
  { id: 'q86', text: 'The treatment for varicose veins includes:', options: ['Compression stockings', 'Immediate surgery', 'Antibiotics', 'Painkillers only'], answerIndex: 0 },
  { id: 'q87', text: 'In septic shock, the initial management is:', options: ['Fluid resuscitation', 'Surgery', 'Antibiotics only', 'Oxygen'], answerIndex: 0 },
  { id: 'q88', text: 'The commonest site of peptic ulcer perforation is:', options: ['Duodenum', 'Stomach', 'Jejunum', 'Ileum'], answerIndex: 0 },
  { id: 'q89', text: 'In head injury, lucid interval is seen in:', options: ['Extradural hematoma', 'Subdural', 'Concussion', 'Contusion'], answerIndex: 0 },
  { id: 'q90', text: 'The sign of compartment syndrome is:', options: ['Pain on passive stretch', 'No pain', 'Swelling only', 'Redness'], answerIndex: 0 },
  { id: 'q91', text: 'The first-line treatment for anal fissure is:', options: ['Sitz bath and fiber', 'Surgery', 'Antibiotics', 'Steroids'], answerIndex: 0 },
  { id: 'q92', text: 'In tetanus, the characteristic feature is:', options: ['Lockjaw (trismus)', 'Fever only', 'Diarrhea', 'Rash'], answerIndex: 0 },
  { id: 'q93', text: 'The commonest cause of urinary retention in elderly males is:', options: ['Benign prostatic hyperplasia', 'Stone', 'Tumor', 'Infection'], answerIndex: 0 },
  { id: 'q94', text: 'In snake bite, the first aid is:', options: ['Immobilization and pressure bandage', 'Tourniquet', 'Cutting wound', 'Sucking venom'], answerIndex: 0 },
  { id: 'q95', text: 'The treatment for dog bite includes:', options: ['Rabies vaccine and immunoglobulin', 'Antibiotics only', 'Tetanus toxoid only', 'Observation'], answerIndex: 0 },
  // Clinical Pathology (96–100)
  { id: 'q96', text: 'The confirmatory test for malaria is:', options: ['Thick and thin blood smear', 'Urine test', 'Stool test', 'X-ray'], answerIndex: 0 },
  { id: 'q97', text: 'In anemia, hemoglobin level below is:', options: ['13 g/dL in males', '10 g/dL', '15 g/dL', '8 g/dL'], answerIndex: 0 },
  { id: 'q98', text: 'The stool test for occult blood is positive in:', options: ['Peptic ulcer bleed', 'Jaundice', 'Diabetes', 'Hypertension'], answerIndex: 0 },
  { id: 'q99', text: 'The commonest organism in urine culture in UTI is:', options: ['E. coli', 'Staphylococcus', 'Streptococcus', 'Pseudomonas'], answerIndex: 0 },
  { id: 'q100', text: 'In typhoid, Widal test shows rising titer of:', options: ['O and H antigens', 'Only O', 'Only H', 'Vi antigen'], answerIndex: 0 },
  // Repeated / High-Yield set (from PDF pages 7–11)
  { id: 'q101', text: 'Cartilage is a type of:', options: ['Epithelial tissue', 'Connective tissue', 'Muscular tissue', 'Nervous tissue'], answerIndex: 1 },
  { id: 'q102', text: 'Sense of smell is:', options: ['Gustation', 'Olfaction', 'Audition', 'Vision'], answerIndex: 1 },
  { id: 'q103', text: 'Bluish discoloration of skin is:', options: ['Pallor', 'Cyanosis', 'Jaundice', 'Erythema'], answerIndex: 1 },
  { id: 'q104', text: 'Diaphragm is supplied by:', options: ['Coronary', 'Phrenic', 'Renal', 'Vasa vasorum arteries'], answerIndex: 1 },
  { id: 'q105', text: 'Normal heart rate per minute:', options: ['50–70', '70–100', '120–160', '140–200'], answerIndex: 1 },
  { id: 'q106', text: 'IMNCI stands for:', options: ['Integrated Mother and Neonatal Care Initiative', 'Integrated Management of Neonatal and Childhood Illness', 'Indian Medical Neonatal Care Institute', 'Infant Mortality and Neonatal Care Integration'], answerIndex: 1 },
  { id: 'q107', text: 'Vitamin A supplementation for children (age group):', options: ['6 months – 5 years', '0–6 months', '5–12 years', 'Adults'], answerIndex: 0 },
  { id: 'q108', text: 'First immunization of a baby:', options: ['Colostrum', 'BCG', 'KMC', 'All'], answerIndex: 1 },
  { id: 'q109', text: 'Waste management in rural areas:', options: ['Incineration', 'Composting/Pit method', 'Landfill', 'Recycling'], answerIndex: 1 },
  { id: 'q110', text: 'Natural source of water:', options: ['Tap', 'Bottled', 'Surface/Ground', 'Filtered'], answerIndex: 2 },
  { id: 'q111', text: 'Water-borne disease:', options: ['TB', 'Cholera', 'Measles', 'HIV'], answerIndex: 1 },
  { id: 'q112', text: 'Most cost-effective family planning method:', options: ['Tubectomy', 'Pills', 'IUD', 'Condoms'], answerIndex: 2 },
  { id: 'q113', text: 'Best method for early medical abortion:', options: ['D&C', 'Mifepristone + Misoprostol', 'Herbal', 'Vacuum'], answerIndex: 1 },
  { id: 'q114', text: 'SWOT stands for:', options: ['Survey of Workers', 'Strengths, Weaknesses, Opportunities, Threats', 'Survey of Women', 'Systematic Oral Water Therapy'], answerIndex: 1 },
  { id: 'q115', text: 'Egg vack enema is used for:', options: ['Fever', 'Constipation/Bowel evacuation', 'Hydration', 'Wound'], answerIndex: 1 },
  { id: 'q116', text: 'Father of modern management:', options: ['Peter Drucker', 'Frederick Winslow Taylor', 'Henry Fayol', 'Max Weber'], answerIndex: 1 },
  { id: 'q117', text: 'Warts are caused by:', options: ['Herpes', 'HPV', 'Staph', 'Fungus'], answerIndex: 1 },
  { id: 'q118', text: 'Impetigo is commonly caused by:', options: ['E. coli', 'Staphylococcus aureus', 'TB', 'Candida'], answerIndex: 1 },
  { id: 'q119', text: 'Jaundice is first observed in:', options: ['Lower limbs', 'Face and sclera', 'RUQ', 'Chest'], answerIndex: 1 },
  { id: 'q120', text: 'Chronic dermatitis:', options: ['Contact', 'Atopic', 'Seborrheic', 'All'], answerIndex: 1 },
  { id: 'q121', text: 'Gonorrhoea is caused by:', options: ['Treponema', 'Neisseria gonorrhoeae', 'Chlamydia', 'E. coli'], answerIndex: 1 },
  { id: 'q122', text: 'Leprosy first affects:', options: ['Skin', 'Lungs', 'Peripheral nerves', 'Liver'], answerIndex: 2 },
  { id: 'q123', text: 'PAP smear detects:', options: ['Breast', 'Cervical cancer', 'Ovarian', 'Endometrial'], answerIndex: 1 },
  { id: 'q124', text: 'Vitamin deficiency in chronic alcoholics:', options: ['C', 'D', 'B1 (Thiamine)', 'A'], answerIndex: 2 },
  { id: 'q125', text: 'Side effect of Tetracycline:', options: ['Hypertension', 'Teeth discoloration', 'Hearing loss', 'Insomnia'], answerIndex: 1 },
  { id: 'q126', text: 'Ethambutol side effect:', options: ['Liver damage', 'Optic neuritis', 'Renal failure', 'Tinnitus'], answerIndex: 1 },
  { id: 'q127', text: 'Dextromethorphan is:', options: ['Antipyretic', 'Antitussive', 'Analgesic', 'Antihistamine'], answerIndex: 1 },
  { id: 'q128', text: 'Unwanted harmful effects of drug:', options: ['Toxic', 'Adverse', 'Side', 'Misuse'], answerIndex: 1 },
  { id: 'q129', text: 'Quinine side effect:', options: ['Coma', 'Deafness', 'Headache', 'Tremors'], answerIndex: 1 },
  { id: 'q130', text: 'Growth hormone is secreted by:', options: ['Thyroid', 'Posterior pituitary', 'Anterior pituitary', 'Adrenal'], answerIndex: 2 },
  { id: 'q131', text: 'Insulin is mainly for:', options: ['Type 2 only', 'Type 1', 'Hypertension', 'Thyroid'], answerIndex: 1 },
  // Additional NHPC questions (pages 969–973)
  { id: 'q132', text: 'What is the most common type of anemia found worldwide?', options: ['Sickle cell anemia', 'Iron deficiency anemia', 'Aplastic anemia', 'Hemolytic anemia'], answerIndex: 1 },
  { id: 'q133', text: 'Which type of water contains the highest concentration of salts?', options: ['Rain water', 'River water', 'Underground water', 'Seas water'], answerIndex: 3 },
  { id: 'q134', text: 'Koplik spots are a characteristic symptom of which disease?', options: ['Chickenpox', 'Measles', 'Mumps', 'Rubella'], answerIndex: 1 },
  { id: 'q135', text: "The 'flag sign' is a clinical indicator of:", options: ['Marasmus', 'Kwashiorkor', 'Rickets', 'Scurvy'], answerIndex: 1 },
  { id: 'q136', text: 'In which stage of syphilis does a painless, firm, round ulcer called a chancre appear?', options: ['Primary stage', 'Secondary stage', 'Latent stage', 'Tertiary stage'], answerIndex: 0 },
  { id: 'q137', text: 'N-acetylcysteine is used as an antidote for which poison?', options: ['Lead poisoning', 'Carbon monoxide', 'Paracetamol (PCM)', 'Cyanide'], answerIndex: 2 },
  { id: 'q138', text: "Which gland is commonly known as the 'emergency gland'?", options: ['Thyroid gland', 'Pituitary gland', 'Adrenal gland', 'Pancreas'], answerIndex: 2 },
  { id: 'q139', text: 'World Health Day is celebrated annually on:', options: ['7th March', '7th April', '7th May', '7th June'], answerIndex: 1 },
  { id: 'q140', text: 'Which is considered the primary function of management?', options: ['Organizing', 'Leading', 'Planning', 'Controlling'], answerIndex: 2 },
  { id: 'q141', text: 'What does HFOMC stand for?', options: ['Health Facilities Operational Management Center', 'Health Facility Operation and Management Committee', 'Hospital Facilities Oversight Management Committee', 'Health Force Operations Management Center'], answerIndex: 1 },
  { id: 'q142', text: 'The Ziehl-Neelsen (ZN) staining test is primarily used to diagnose which condition?', options: ['Viral infections', 'Bacterial infections', 'Latent malaria disease', 'Tuberculosis'], answerIndex: 3 },
  { id: 'q143', text: 'How many pairs of cranial nerves are present in the human body?', options: ['10 pairs', '11 pairs', '12 pairs', '13 pairs'], answerIndex: 2 },
  { id: 'q144', text: 'Which is the most effective treatment for sexually transmitted diseases like gonorrhea and syphilis?', options: ['Antiviral medication', 'Antibiotics', 'Antifungal medication', 'Immunotherapy'], answerIndex: 1 },
  { id: 'q145', text: 'The Glasgow Coma Scale is used to measure:', options: ['Pain level', 'Consciousness level', 'Blood pressure', 'Fever intensity'], answerIndex: 1 },
  { id: 'q146', text: 'Which type of epistaxis typically requires nasal packing?', options: ['Anterior epistaxis', 'Posterior epistaxis', 'Lateral epistaxis', 'Superior epistaxis'], answerIndex: 1 },
  { id: 'q147', text: 'Which of the following is a vector-borne disease?', options: ['Influenza', 'Dengue', 'Tuberculosis', 'HIV'], answerIndex: 1 },
  { id: 'q148', text: 'There are some undesirable but unavoidable pharmacodynamics effects of a drug, which are known as:', options: ['Intolerance', 'Idiosyncrasy', 'Side effects', 'Toxic effect'], answerIndex: 2 },
  { id: 'q149', text: 'Which of the following is a body-penetrating parasite?', options: ['Tapeworm', 'Roundworm', 'Hook worm', 'Pinworm'], answerIndex: 2 },
  { id: 'q150', text: 'In emergency triage, which color typically represents a life-threatening condition?', options: ['Green', 'Yellow', 'Red', 'Black'], answerIndex: 2 },
  { id: 'q151', text: 'What is the recommended home management for some dehydration?', options: ['IV fluids', 'ORS', 'Plain water', 'RUTF'], answerIndex: 1 },
  { id: 'q152', text: 'What is the vitamin A dose recommended for a 9-month-old child?', options: ['10,000 IU', '100,000 IU', '150,000 IU', '200,000 IU'], answerIndex: 1 },
  { id: 'q153', text: 'What is the first aid step for a snake bite?', options: ['Apply tourniquet', 'Suck out the venom', 'Immobilize bite part', 'Apply hot compress'], answerIndex: 2 },
  { id: 'q154', text: 'What is the correct storage temperature range for a cold place in HP level storage?', options: ['0°C to 4°C', '+2°C to +8°C', '-2°C to +2°C', '+4°C to +10°C'], answerIndex: 1 },
  { id: 'q155', text: "The goal for 'Good health and well-being' is represented by which SDG number?", options: ['Goal-1', 'Goal-2', 'Goal-3', 'Goal-4'], answerIndex: 2 },
  { id: 'q156', text: 'Which of the following is NOT a part of male reproductive system?', options: ['Prostate', 'Testicles', 'Uterus', 'Penis'], answerIndex: 2 },
  { id: 'q157', text: 'What is the normal platelet count range?', options: ['50,000 - 100,000', '100,000 - 200,000', '150,000 - 400,000', '500,000 - 750,000'], answerIndex: 2 },
  { id: 'q158', text: 'What is the typical incubation period for scrub typhus fever?', options: ['5-7 days', '8-9 days', '10-12 days', '15-20 days'], answerIndex: 2 },
  { id: 'q159', text: 'What is the likely diagnosis for a 45-year-old male presenting with vomiting and severe epigastric pain?', options: ['Gastritis', 'Acute pancreatitis', 'Peptic ulcer', 'Gastroenteritis'], answerIndex: 1 },
  { id: 'q160', text: 'Which type of sugar is typically used to make medicinal syrup?', options: ['Glucose', 'Fructose', 'Sucrose', 'Maltose'], answerIndex: 2 },
  { id: 'q161', text: 'A 5-month-old baby presents with a sunken fontanelle. What could this indicate?', options: ['Overhydration', 'Dehydration', 'Normal development', 'Excessive growth'], answerIndex: 1 },
  { id: 'q162', text: 'Which component contains inorganic calculus?', options: ['Blood', 'Urine', 'Saliva', 'Plaque'], answerIndex: 3 },
  { id: 'q163', text: 'Which sample works as an equally based probability?', options: ['Stratified sample', 'Random sample', 'Systematic sample', 'Cluster sample'], answerIndex: 1 },
  { id: 'q164', text: 'The amount of sewage flowing in a system in 24 hours is called:', options: ['Sewage rate', 'Dry weather flow', 'RCA index', 'Effluent rate'], answerIndex: 1 },
  { id: 'q165', text: 'At what age does a baby receive the PCV vaccine for pneumonia?', options: ['6 weeks, 10 weeks, and 9 months', '6 weeks, 10 weeks, and 9 weeks', '6 weeks, 10 weeks, and 14 months', '6 weeks, 10 weeks, and 14 weeks'], answerIndex: 0 },
  { id: 'q166', text: 'In the day of mythology, the symbol Rx was considered as a prayer to:', options: ['Jupiter', 'Jesus', 'Neptune', 'Dhanvantari'], answerIndex: 0 },
  { id: 'q167', text: 'The movable bone of the cranial joint is?', options: ['Frontal bone', 'Parietal bone', 'Mandible', 'Occipital bone'], answerIndex: 2 },
  { id: 'q168', text: 'What is the common treatment of urticaria?', options: ['Antibiotics', 'Antihistamines', 'Steroids', 'Painkillers'], answerIndex: 1 },
  { id: 'q169', text: 'A solid elevated skin lesion, less than 0.5 cm in diameter, is called:', options: ['Papule', 'Vesicle', 'Bulla', 'Nodule'], answerIndex: 0 },
  { id: 'q170', text: 'Bluish discoloration of skin and mucous membranes is called:', options: ['Cyanosis', 'Erythema', 'Jaundice', 'Pallor'], answerIndex: 0 },
  { id: 'q171', text: 'The volume of air that remains in the lungs even after a maximal expiration effort is called:', options: ['Vital capacity', 'Expiratory reserve volume', 'Residual volume', 'Functional residual capacity'], answerIndex: 2 },
  { id: 'q172', text: 'The pituitary gland is anatomically located in:', options: ['Sella turcica of sphenoid bone', 'Frontal bone', 'Temporal bone', 'Occipital bone'], answerIndex: 0 },
  { id: 'q173', text: 'Nephrotic syndrome is characterized by all EXCEPT:', options: ['Massive proteinuria', 'Edema', 'Hematuria', 'Hypoalbuminemia'], answerIndex: 2 },
  { id: 'q174', text: 'Which drugs belong to the second generation cephalosporins?', options: ['Cefazolin and Cephalexin', 'Cefuroxime, Cefaclor, and Cefoxitin', 'Ceftriaxone and Cefotaxime', 'Cefepime'], answerIndex: 1 },
  { id: 'q175', text: 'What is the drug of choice for treating Neisseria gonorrhoeae infection?', options: ['Penicillin', 'Ceftriaxone', 'Azithromycin', 'Doxycycline'], answerIndex: 1 },
  { id: 'q176', text: 'Which statement is correct about antiretroviral therapy for HIV/AIDS?', options: ['It uses only one drug', 'Zidovudine, Lamivudine, and Nevirapine are used', 'It cures HIV completely', "It's only used in terminal stages"], answerIndex: 1 },
  { id: 'q177', text: 'How many cartilages are present in the larynx?', options: ['7', '8', '9', '10'], answerIndex: 2 },
  { id: 'q178', text: 'Oral Rehydration Salts (ORS) Day is celebrated every year on:', options: ['29 January', '29 March', '29 July', '29 August'], answerIndex: 2 },
  { id: 'q179', text: 'Diabetes mellitus is treated by which of the following?', options: ['Antihypertensive drugs', 'Insulin and oral hypoglycemic drugs', 'Antibiotics', 'Painkillers'], answerIndex: 1 },
  { id: 'q180', text: 'Scabies is primarily transmitted by which of the following?', options: ['Airborne transmission', 'Skin-to-skin contact', 'Waterborne transmission', 'Ingestion of contaminated food'], answerIndex: 1 },
  { id: 'q181', text: 'Screening for diseases is part of which level of prevention?', options: ['Primary level', 'Secondary level', 'Tertiary level', 'Quaternary level'], answerIndex: 1 },
  { id: 'q182', text: 'What is the process of adding nutritious content to food called?', options: ['Food adulteration', 'Food irradiation', 'Food fortification', 'Food pasteurization'], answerIndex: 2 },
  { id: 'q183', text: 'In breast cancer metastatic conditions, which tissue is mainly affected?', options: ['Bone', 'Liver', 'Brain', 'Skin'], answerIndex: 0 },
  { id: 'q184', text: 'What is the length of the Eustachian tube?', options: ['2.5 cm', '3.6 cm', '4.5 cm', '5.6 cm'], answerIndex: 1 },
  { id: 'q185', text: 'Which is the most common causative agent of urinary tract infections (UTIs)?', options: ['Staphylococcus aureus', 'Escherichia coli', 'Pseudomonas aeruginosa', 'Klebsiella pneumoniae'], answerIndex: 1 },
  { id: 'q186', text: 'Epinephrine and Salbutamol are given in emergency conditions for:', options: ['Heart attack', 'Hypertension', 'Asthma', 'Diabetes'], answerIndex: 2 },
  { id: 'q187', text: 'Sucrose is a combination of which two monosaccharides?', options: ['Glucose + Glucose', 'Glucose + Fructose', 'Fructose + Galactose', 'Glucose + Lactose'], answerIndex: 1 },
  { id: 'q188', text: 'Which gas is commonly used to sterilize OT equipment?', options: ['Ozone gas', 'Chlorine gas', 'Ethylene oxide gas', 'Nitrogen gas'], answerIndex: 2 },
  { id: 'q189', text: 'Culex mosquitoes are typically found in which environment?', options: ['Forests', 'Stagnant or dirty water', 'Fresh running water', 'Hot deserts'], answerIndex: 1 },
  { id: 'q190', text: 'Delusion is defined as which of the following?', options: ['Excessive fear', 'False and unshakable belief', 'Impaired memory', 'Difficulty in speech'], answerIndex: 1 },
  { id: 'q191', text: 'Which of the following contains 33% chlorine?', options: ['Bleaching powder', 'Chlorinated water', 'Sodium chloride', 'Saltwater'], answerIndex: 0 },
  { id: 'q192', text: 'Immunity gained by a fetus from its mother is an example of:', options: ['Active immunity', 'Natural passive immunity', 'Artificial immunity', 'Innate immunity'], answerIndex: 1 },
  { id: 'q193', text: 'What is the causative agent of rabies?', options: ['Type I Lyssa virus', 'Influenza virus', 'Hepatitis virus', 'Mycobacterium tuberculosis'], answerIndex: 0 },
  { id: 'q194', text: 'Ivermectin is the drug of choice for which condition?', options: ['Malaria', 'Tuberculosis', 'Scabies', 'Pneumonia'], answerIndex: 2 },
  { id: 'q195', text: 'Atropine is the antidote for which types of poisoning?', options: ['Lead and mercury', 'Mushroom and OP', 'Snake bite', 'Carbon monoxide'], answerIndex: 1 },
  { id: 'q196', text: 'What type of communication is a lecture considered as?', options: ['Two-way', 'One-way', 'Interactive', 'Group'], answerIndex: 1 },
  { id: 'q197', text: 'Which immunoglobulin rises during an allergic condition?', options: ['IgA', 'IgE', 'IgG', 'IgM'], answerIndex: 1 },
  { id: 'q198', text: 'The organ of Corti is located in which part of the ear?', options: ['Tympanic membrane', 'Cochlea', 'Semicircular canals', 'Vestibule'], answerIndex: 1 },
  { id: 'q199', text: 'Warfarin is classified as which type of medication?', options: ['Antihypertensive', 'Anticoagulant', 'Antibiotic', 'Antiemetic'], answerIndex: 1 },
  { id: 'q200', text: 'What is the transplantation of graft between genetically identical individuals?', options: ['Allogenic graft', 'Autograft', 'Xenograft', 'Isograft'], answerIndex: 3 },
  { id: 'q201', text: 'What is the most common causative agent of diarrhea in children?', options: ['Norovirus', 'Rotavirus', 'Salmonella', 'E. coli'], answerIndex: 1 },
  { id: 'q202', text: 'The clotting of blood is delayed by:', options: ['Vitamin K', 'Heparin', 'Calcium', 'Platelets'], answerIndex: 1 },
  { id: 'q203', text: 'What is a mammogram primarily used for?', options: ['Lung cancer', 'Breast cancer', 'Kidney stones', 'Arrhythmias'], answerIndex: 1 },
  { id: 'q204', text: 'In emphysema, which part of the respiratory system becomes permanently dilated?', options: ['Trachea', 'Bronchioles', 'Alveoli', 'Bronchi'], answerIndex: 2 },
  { id: 'q205', text: 'The accumulation of blood in the pleural cavity is called:', options: ['Pneumothorax', 'Hemothorax', 'Hydrothorax', 'Empyema'], answerIndex: 1 },
  { id: 'q206', text: 'According to WHO, the adolescent age group is defined as:', options: ['5 to 10 years', '10 to 19 years', '12 to 18 years', '15 to 25 years'], answerIndex: 1 },
  { id: 'q207', text: 'How many calories does 1 gram of fat contain?', options: ['4 calories', '6 calories', '7 calories', '9 calories'], answerIndex: 3 },
  { id: 'q208', text: "The greater omentum is referred to as the 'policeman' of the:", options: ['Chest', 'Abdomen', 'Brain', 'Lungs'], answerIndex: 1 },
  { id: 'q209', text: 'What type of tissue connects bone to bone?', options: ['Tendon', 'Ligament', 'Cartilage', 'Muscle'], answerIndex: 1 },
  { id: 'q210', text: 'Which vein is most commonly used for blood collection?', options: ['Jugular vein', 'Basilic vein', 'Median cubital vein', 'Cephalic vein'], answerIndex: 2 },
  { id: 'q211', text: 'Optic neuritis is a side effect of which medication?', options: ['Rifampicin', 'Ethambutol', 'Isoniazid', 'Streptomycin'], answerIndex: 1 },
  { id: 'q212', text: 'The capacity of a drug to cause fetal abnormalities is called:', options: ['Mutagenicity', 'Carcinogenicity', 'Teratogenicity', 'Allergenicity'], answerIndex: 2 },
  { id: 'q213', text: 'What is the definitive treatment for phimosis?', options: ['Antibiotics', 'Steroid creams', 'Circumcision', 'Catheterization'], answerIndex: 2 },
  { id: 'q214', text: 'The adrenal gland is commonly known as the:', options: ['Insulin gland', 'Cortisol gland', 'Emergency gland', 'Thyroxine gland'], answerIndex: 2 },
  { id: 'q215', text: 'Weakness, dizziness, and confusion are symptoms of which shock?', options: ['Cardiogenic', 'Septic', 'Hypovolemic', 'Neurogenic'], answerIndex: 2 },
  { id: 'q216', text: 'What is the unit of protein?', options: ['Peptide', 'Amino acid', 'Nucleotide', 'Glucose'], answerIndex: 1 },
  { id: 'q217', text: 'Which of the following causes massive hemoptysis?', options: ['Pneumonia', 'TB/Bronchiectasis', 'Lung cancer', 'Pulmonary embolism'], answerIndex: 1 },
  { id: 'q218', text: 'What is the common cause of gangrene?', options: ['Viral infection', 'Fungal infection', 'Bacterial infection', 'Parasitic infection'], answerIndex: 2 },
  { id: 'q219', text: 'The primary function of bile salt is to:', options: ['Digest proteins', 'Emulsify lipids', 'Break down carbs', 'Activate enzymes'], answerIndex: 1 },
  { id: 'q220', text: 'Which taste is sensed on the lateral side of the tongue?', options: ['Sweet', 'Bitter', 'Sour', 'Salty'], answerIndex: 2 },
  { id: 'q221', text: 'What is the first sign of inflammation?', options: ['Rubor', 'Calor', 'Dolor', 'Pallor'], answerIndex: 1 },
  { id: 'q222', text: 'Which is true about dextromethorphan?', options: ['Antibiotic', 'Antitussive', 'Antipyretic', 'Antiemetic'], answerIndex: 1 },
  { id: 'q223', text: 'The most common jaundice in pregnancy is:', options: ['Hepatitis A', 'Hepatitis B', 'Hepatitis C', 'Hepatitis E'], answerIndex: 3 },
  { id: 'q224', text: 'How much water does an adult need per day?', options: ['1 litre', '1.5 litre', '2 litre', '2.5 litre'], answerIndex: 2 },
  { id: 'q225', text: 'What is the most common type of blood group?', options: ['A', 'B', 'AB', 'O'], answerIndex: 3 },
  { id: 'q226', text: 'The normal potassium level in blood is:', options: ['2.5 mEq/L', '3.5 to 5.0 mEq/L', '5.0 to 6.0 mEq/L', '20.0 mEq/L'], answerIndex: 1 },
  { id: 'q227', text: 'The common site for volvulus in children is:', options: ['Ascending colon', 'Transverse colon', 'Sigmoid colon', 'Descending colon'], answerIndex: 2 },
  { id: 'q228', text: 'The normal urine output per day is:', options: ['500-1000 mL', '1000-1500 mL', '1500-2000 mL', '150-200 mL'], answerIndex: 1 },
  { id: 'q229', text: 'Which organ lies deep in the right hypochondriac region?', options: ['Spleen', 'Liver', 'Stomach', 'Duodenum'], answerIndex: 1 },
  { id: 'q230', text: 'Lumbar puncture is contraindicated in:', options: ['Head injury', 'Fever', 'Raised ICP', 'Meningitis'], answerIndex: 2 },
  { id: 'q231', text: 'Heparin is produced by:', options: ['Kidney', 'Liver', 'Lungs', 'Stomach'], answerIndex: 2 },
  // NHPC Licensing Examination Practice Questions (2081 - Jestha, pages 961-967)
  { id: 'q232', text: 'The most common site of tuberculosis (TB) infection is:', options: ['Brain', 'Lungs', 'Kidneys', 'Heart'], answerIndex: 1 },
  { id: 'q233', text: 'The eye lies in the .......cavity.', options: ['Oral', 'Cranial', 'Orbital', 'Nasal'], answerIndex: 2 },
  { id: 'q234', text: 'Cranial nerves are part of the:', options: ['Central nervous system', 'Peripheral nervous system', 'Autonomic nervous system', 'Somatic nervous system'], answerIndex: 1 },
  { id: 'q235', text: 'Cold compression is commonly used for:', options: ['Increasing blood flow', 'Reducing inflammation', 'Enhancing digestion', 'Improving sleep'], answerIndex: 1 },
  { id: 'q236', text: 'The weight of the thyroid gland is about:', options: ['10-15 gm', '25 gm', '40 gm', 'Less than 10 gm'], answerIndex: 1 },
  { id: 'q237', text: 'How many blood vessels are found in the umbilical cord?', options: ['1 vein and 1 artery', '1 vein and 2 arteries', '2 veins and 1 artery', '2 veins and 2 arteries'], answerIndex: 1 },
  { id: 'q238', text: 'Which drug is contraindicated in peptic ulcer disease?', options: ['Iron', 'Aspirin', 'Antacids', 'Antibiotics'], answerIndex: 1 },
  { id: 'q239', text: 'Early diagnosis and treatment fall under the.........level of prevention.', options: ['Primordial', 'Primary', 'Secondary', 'Tertiary'], answerIndex: 2 },
  { id: 'q240', text: 'Pantoprazole is an example of:', options: ['Proton pump inhibitors', 'H2 receptor antagonists', 'Anticholinergic', 'Diuretics'], answerIndex: 0 },
  { id: 'q241', text: 'What causes uterine contractions?', options: ['Increased hydration', 'Hormonal changes', 'Physical exercise', 'High calcium intake'], answerIndex: 1 },
  { id: 'q242', text: 'Hoarseness of voice is a common symptom of:', options: ['Typhoid', 'Laryngitis', 'Tonsillitis', 'APD'], answerIndex: 1 },
  { id: 'q243', text: 'Which of the following glands is also called the master gland?', options: ['Thyroid gland', 'Pituitary gland', 'Pineal gland', 'Thymus gland'], answerIndex: 1 },
  { id: 'q244', text: 'The causative agent of gonorrhea is:', options: ['Treponema pallidum', 'Haemophilus ducreyi', 'Neisseria gonorrhoeae', 'Candida albicans'], answerIndex: 2 },
  { id: 'q245', text: 'Mental health problems are most commonly seen in:', options: ['Infants', 'Adolescents', 'Middle-aged adults', 'Elderly people'], answerIndex: 1 },
  { id: 'q246', text: 'The elimination level of leprosy is defined as:', options: ['Case notification rate <1 per 100', 'Incidence <1 per 1000', 'Prevalence <1 per 10000', 'Prevalence <1 per 100000'], answerIndex: 2 },
  { id: 'q247', text: 'What is a prodrug?', options: ['Inactive drug converted into an active metabolite', 'Active drug converted into an inactive metabolite', 'Measures drug safety or not', 'Binds to a receptor and elicits a biological response'], answerIndex: 0 },
  { id: 'q248', text: "What percentage of salicylic acid is in Whitfield's ointment?", options: ['3%', '6%', '9%', '12%'], answerIndex: 1 },
  { id: 'q249', text: 'The incubation period of gonorrhea is:', options: ['4-6 weeks', '2-7 days', '10-14 days', '18-24 days'], answerIndex: 1 },
  { id: 'q250', text: 'Sensory neural deafness is:', options: ['Deafness due to a blocked ear', 'Deafness due to impairment of the 8th cranial nerve', 'Deafness due to trauma', 'Deafness due to imbalance air pressure'], answerIndex: 1 },
  { id: 'q251', text: 'The outer layer of the skin is called:', options: ['Dermis', 'Epidermis', 'Hypodermis', 'Mid layer'], answerIndex: 1 },
  { id: 'q252', text: 'In which of the following diseases does the skin color change to white spots (milky)?', options: ['Vitiligo', 'Scabies', 'Impetigo', 'Tinea'], answerIndex: 0 },
  { id: 'q253', text: 'The number of lobes in the right lung is:', options: ['2 lobes', '3 lobes', '4 lobes', '5 lobes'], answerIndex: 1 },
  { id: 'q254', text: 'The most common cause of chronic pancreatitis is:', options: ['Gallstones', 'Alcohol', 'Drugs', 'Injury'], answerIndex: 1 },
  { id: 'q255', text: 'Which of the following medicines is contraindicated for alcoholic patients?', options: ['Thiamine', 'Paracetamol', 'Metronidazole', 'Dextrose 5%'], answerIndex: 2 },
  { id: 'q256', text: 'Valproic acid is used for:', options: ['Anti-anxiety', 'Anti-depressants', 'Anti-epileptics', 'Mood stabilizer'], answerIndex: 2 },
  { id: 'q257', text: 'A positive Babinski sign indicates:', options: ['Hypertension', 'Diabetes mellitus', 'Stroke', 'Myocardial infarction'], answerIndex: 2 },
  { id: 'q258', text: 'For dental plaque to mature, it takes a minimum of:', options: ['2 hours', '6 hours', '12 hours', '24 hours'], answerIndex: 3 },
  { id: 'q259', text: 'Which of the following method is not followed while doing physical examination?', options: ['Smelling', 'Auscultation', 'Tasting', 'Measurement'], answerIndex: 0 },
  { id: 'q260', text: 'The causative agent of a boil is:', options: ['Clostridium perfringens', 'Streptococcus', 'Staphylococcus aureus', 'E. coli'], answerIndex: 2 },
  { id: 'q261', text: 'The duration of the first stage of labor in a primigravida is:', options: ['8-10 hours', '1-2 hours', '15-30 minutes', '12 hours'], answerIndex: 0 },
  { id: 'q262', text: "During an otoscopic examination, which action should be avoided to prevent the client from discomfort and injury?", options: ["Tipping the client's head away from the examiner", 'Inserting the otoscope inferiorly into the distal portion of the external canal', 'Inserting the otoscope superiorly into the proximal two-thirds of the external canal', "Bracing the examiner's hand against the client's head"], answerIndex: 2 },
  { id: 'q263', text: 'The most common site of epistaxis is:', options: ['Medial segment', 'Lateral segment', 'Anterior segment of the nostril', 'Posterior segment'], answerIndex: 2 },
  { id: 'q264', text: 'The most common cause of food poisoning with symptoms presenting within 4-6 hours is:', options: ['Staphylococcus poisoning', 'E. coli', 'Shigella', 'Salmonella'], answerIndex: 0 },
  { id: 'q265', text: "Which is/ are NOT X-linked disorders?", options: ["Wilson's disease", 'Thalassemia', 'BO blood groups system', 'All of the above'], answerIndex: 3 },
  { id: 'q266', text: 'Gum bleeding is caused by a deficiency of:', options: ['Vitamin B', 'Vitamin C', 'Vitamin D', 'Vitamin E'], answerIndex: 1 },
  { id: 'q267', text: 'The abbreviation H.S. means:', options: ['Before meal', 'If necessary', 'At bedtime', 'After meal'], answerIndex: 2 },
  { id: 'q268', text: 'Which one is the originator of the message?', options: ['Message', 'Channel', 'Communicator', 'Audience'], answerIndex: 2 },
  { id: 'q269', text: 'Which period is referred to as the puerperium period?', options: ['During pregnancy', 'Immediately after childbirth to 42 days', 'During adolescence', 'During menopause'], answerIndex: 1 },
  { id: 'q270', text: 'Glucose and fructose are:', options: ['Disaccharides', 'Polysaccharides', 'Oligosaccharides', 'Monosaccharides'], answerIndex: 3 },
  { id: 'q271', text: "The term 'teratogen' is defined as:", options: ['Causing abnormal fetal development', 'Causing abnormal labor', 'Causing abnormal implantation', 'Causing abortion'], answerIndex: 0 },
  { id: 'q272', text: 'Drugs that act on the H1 receptor are classified as:', options: ['Antihistamine', 'Proton pump inhibitors', 'Antibiotics', 'None of the above'], answerIndex: 0 },
  { id: 'q273', text: 'Patient was able to read the newsprint at a distance of:', options: ['8 inches', '10 inches', '20 inches', '25 inches'], answerIndex: 1 },
  { id: 'q274', text: 'The best measure of rodent control is:', options: ['Fumigation', 'Trapping', 'Environmental sanitation', 'Rodenticides'], answerIndex: 2 },
  { id: 'q275', text: 'For the detection of Shigella, which test is done:', options: ['Polymerase chain reaction (PCR)', 'E. coli', 'Widal', "Both 'B' and 'C'"], answerIndex: 0 },
  { id: 'q276', text: 'The drug used in kala-azar is:', options: ['Quinine', 'Miltefosine', 'Sodium stibogluconate', "Both 'B' and 'C'"], answerIndex: 3 },
  { id: 'q277', text: 'The exocrinal part of the pancreas is related to the:', options: ['Endocrine system', 'Digestive system', 'Reticuloendothelial system', 'Cardiovascular system'], answerIndex: 1 },
  { id: 'q278', text: 'Skin color in gangrene:', options: ['Red', 'White', 'Blue', 'Black'], answerIndex: 3 },
  { id: 'q279', text: 'Which is not under STI?', options: ['Syphilis', 'Gonorrhea', 'Chlamydia', 'UTI'], answerIndex: 3 },
  { id: 'q280', text: 'The abbreviation used to record oxygen saturation as measured by a pulse oximeter is:', options: ['SaO2', 'PCO2', 'PO2', 'SpO2'], answerIndex: 3 },
  { id: 'q281', text: 'The condition for legal abortion in the case of rape or incest is up to:', options: ['12 weeks', '18 weeks', '22 weeks', '28 weeks'], answerIndex: 3 },
  { id: 'q282', text: 'Which of the following statement is correct about febrile convulsions in children?', options: ['The convulsion occurs only after a warning sign', 'Febrile convulsion is a common medical condition in children', 'The brain activity is normal during the convulsion', 'None of the above'], answerIndex: 1 },
  { id: 'q283', text: 'Which of the following is not a general principle of the bandage application?', options: ['A bandage should be applied directly over the wound', 'It should be used only to hold the dressing that covers the wound', 'It should be applied firmly and fastened securely', 'It should not be applied very tightly or very loosely'], answerIndex: 0 },
  { id: 'q284', text: 'The cluster test is done in:', options: ['Tuberculosis', 'Leprosy', 'STD', 'Malaria'], answerIndex: 2 },
  { id: 'q285', text: 'The most common nutritional anemia is:', options: ['Iodine deficiency', 'Vitamin B12 deficiency', 'Iron deficiency', 'Folate deficiency'], answerIndex: 2 },
  { id: 'q286', text: 'The dose of a zinc tablet for a 2-6 months old child is:', options: ['10 mg/OD for 10 days', '20 mg/OD for 10 days', '10 mg/BD for 10 days', '20 mg/QID for 10 days'], answerIndex: 0 },
  { id: 'q287', text: 'Which of the following is an anti-helminthic drug?', options: ['Metronidazole', 'Tinidazole', 'Mebendazole', 'Tetracycline'], answerIndex: 2 },
  { id: 'q288', text: 'According to NDHS-2022, what percentage of under 5 years children are stunted in Nepal?', options: ['22%', '36%', '17%', '25%'], answerIndex: 3 },
  { id: 'q289', text: 'Which is not included in the definition of health as per the WHO definition?', options: ['Social', 'Physical', 'Sexual', 'Mental'], answerIndex: 2 },
  { id: 'q290', text: '.......is a continuous process of optimizing opportunities to maintain and improve physical and mental health, independence, and quality of life throughout the life course.', options: ['Development', 'Gerontology', 'Aging', 'Healthy aging'], answerIndex: 3 },
  { id: 'q291', text: 'The HPV vaccine is administered by:', options: ['IM', 'IV', 'ID', 'SC'], answerIndex: 0 },
  { id: 'q292', text: 'The GATHER approach is related to:', options: ['Waste management', 'Counseling', 'Community diagnosis', 'Water purification'], answerIndex: 1 },
  { id: 'q293', text: 'Endemic refers to:', options: ['Disease that has a low rate of occurrence but that is constantly present in a community or region', 'An attack rate in excess of 10 per 1,000 population', 'The occurrence of illnesses of similar nature clearly in excess of the normal expectation for that population at that time', 'Diseases that occur with similar prevalence'], answerIndex: 0 },
  { id: 'q294', text: 'Any loss or abnormality of a psychological, physiological, or anatomical structure or function is called:', options: ['Disability', 'Handicapped', 'Infirmity', 'Impairment'], answerIndex: 3 },
  { id: 'q295', text: 'Health promotion priorities action areas are EXCEPT:', options: ['Building healthy public policy', 'Creating supportive environment', 'Mediate health actions', 'Reorienting health services'], answerIndex: 2 },
  { id: 'q296', text: 'Which one is related to the management of chronic alcoholism?', options: ['Rehabilitation', 'Management of withdrawal symptom', 'Psychiatric support', 'All of the above'], answerIndex: 3 },
  { id: 'q297', text: 'The first step in management of acute retention of urine is:', options: ['Hot compression', 'Catheterization', 'Prescribe medicine', 'Consult to medical doctor'], answerIndex: 0 },
  { id: 'q298', text: 'In Blood bank, the anticoagulant used for preservation of blood is:', options: ['CPD', 'ACD', 'CPDA', 'ADTA'], answerIndex: 2 },
  { id: 'q299', text: 'Lipase enzyme is increased in:', options: ['Acute Pancreatitis', 'Carcinoma of Pancreas', "Both 'A' and 'B'", 'Leukemia'], answerIndex: 2 },
  { id: 'q300', text: 'Hydatid disease is caused by:', options: ['Ancylostoma duodenale', 'Echinococcus granulosus', 'Hymenolepsis nana', 'Enterobius Vermicularis'], answerIndex: 1 },
  { id: 'q301', text: 'In which of the following there is no two-way communication?', options: ['Lecture', 'Symposium', 'Group discussion', 'Counseling'], answerIndex: 0 },
  { id: 'q302', text: 'Which of the following is the universal antidote?', options: ['Heparin', 'Activated charcoal', 'PAM', 'Lignocaine'], answerIndex: 1 },
  { id: 'q303', text: 'ORS (Oral Rehydration Solution) is primarily used for:', options: ['Treating fever', 'Hydrating patients with diarrhea', 'Curing infections', 'Managing hypertension'], answerIndex: 1 },
  { id: 'q304', text: 'Addition of nutritious substances in food is called:', options: ['Preservation', 'Additives', 'Fortification', 'Adulteration'], answerIndex: 2 },
  { id: 'q305', text: 'Deficiency of ....... has been associated with enamel defects and increased risk of dental caries.', options: ['Vitamin A', 'Folic acid', 'Vitamin C', 'Vitamin D'], answerIndex: 3 },
  { id: 'q306', text: 'LMIS stands for:', options: ['Logistics management information system', 'Logistics aid management information system', 'Logical management information system', 'Logistic manipulator information system'], answerIndex: 0 },
  { id: 'q307', text: 'Catch up, keep up and follow up is the strategy for:', options: ['Polio eradication', 'Measles elimination', 'Malaria control', 'Leprosy elimination'], answerIndex: 1 },
  { id: 'q308', text: 'Mumps most commonly involves:', options: ['Parotid glands', 'Sublingual gland', 'Submandibular gland', 'Prostate'], answerIndex: 0 },
  { id: 'q309', text: 'Burrows of scabies are located in:', options: ['Stratum corneum', 'Stratus germinativum', 'Dermis', 'Stratum malpighii'], answerIndex: 0 },
  { id: 'q310', text: 'Which of the following is the most common type of renal colic is:', options: ['Calcium oxalate', 'Calcium phosphate', 'Cystic', 'Uric acid'], answerIndex: 0 },
  { id: 'q311', text: 'Cholecystitis is the inflammation of:', options: ['Gallbladder', 'Urinary bladder', 'Kidney', 'Urethra'], answerIndex: 0 },
  { id: 'q312', text: 'The normal discharge at the end of the second week is called:', options: ['Lochia rubra', 'Lochia Serosa', 'Lochia Alba', 'Lochia Mixed'], answerIndex: 1 },
  { id: 'q313', text: 'Which of the following is the most heat sensitive vaccine?', options: ['Tetanus', 'Pertussis', 'Measles', 'Polio'], answerIndex: 3 },
  { id: 'q314', text: 'In healthcare management, what is the term for the process of allocating resources efficiently to achieve healthcare goals and objectives?', options: ['Health assessment', 'Health promotion', 'Health planning', 'Health financing'], answerIndex: 2 },
  { id: 'q315', text: 'Which of the article in Constitution of Nepal is directly linked with health rights of the citizen?', options: ['Article 22', 'Article 34', 'Article 35', 'Article 36'], answerIndex: 2 },
  { id: 'q316', text: 'Which is the indicator of acute malnutrition?', options: ['Stunting', 'Wasting', 'Undernutrition', 'Overweight'], answerIndex: 1 },
  { id: 'q317', text: 'What is the primary goal of palliative care?', options: ['To cure the underlying disease', 'To prolong life at all costs', 'To relieve suffering and improve the quality of life for patients with serious illnesses', 'To perform surgical interventions'], answerIndex: 2 },
  { id: 'q318', text: 'While inserting NG Tube, length is measured as distance:', options: ['From tip of nose to xiphistermum', 'from tip of nose to umbilicus', 'From tip of nose to earlobe to xiphisternum', 'From mouth to earlobe to xiphisternum'], answerIndex: 2 },
  { id: 'q319', text: 'The response of mammalian living tissue against stimulus; characterized by redness, hot, tender, swelling and loss in function is called:', options: ['Infection', 'Infestation', 'Inflammation', 'Contamination'], answerIndex: 2 },
  { id: 'q320', text: 'The most specific test for alcohol use detection is:', options: ['M.P', 'AST', 'GGT', 'ALT'], answerIndex: 2 },
  { id: 'q321', text: 'Sucrose consists of:', options: ['Glucose and Glucose', 'Glucose and Fructose', 'Glucose and Galactose', 'Fructose and Galactose'], answerIndex: 1 },
  { id: 'q322', text: 'Probability of dying between birth and exactly five years of age expressed per 1,000 live births:', options: ['Birth rate', 'Under five mortality rate', 'Death rate', 'None of these'], answerIndex: 1 },
  { id: 'q323', text: 'Atropine overdose may cause which one of the following:', options: ['Gastrointestinal smooth muscle cramping', 'Increased cardiac rate', 'Increased gastric secretion', 'Pupillary constriction'], answerIndex: 1 },
  { id: 'q324', text: 'For elimination of measles, how much coverage of both doses of measles-rubella vaccination is required?', options: ['>= 90%', '>= 95%', '>= 99%', '100%'], answerIndex: 1 },
  { id: 'q325', text: 'Neonatal jaundice that is developed within 24 hours after birth is:', options: ['Physiological jaundice', 'Pathological jaundice', 'Hemolytic jaundice', 'Hepatic jaundice'], answerIndex: 1 },
  { id: 'q326', text: 'Thermometer is best sterilized by:', options: ['Isopropyl', 'Glutaraldehyde', 'Formaldehyde', 'Ethylene oxide'], answerIndex: 1 },
  { id: 'q327', text: 'Which one of the following is NOT properly matched?', options: ['World Environment Day - 5th June', 'World Health Day - 7th April', 'World Population Day - 15th July', 'World AIDS Day - 1st December'], answerIndex: 2 },
  { id: 'q328', text: 'The type of epidemiology which deals with the risk factors of disease is:', options: ['Descriptive', 'Analytical', 'Experimental', 'Interventional'], answerIndex: 1 },
  { id: 'q329', text: 'Commonest organ structure injured during mastoid surgery:', options: ['Parotid', 'Superficial temporal artery', 'Facial nerve', 'Maxillary artery'], answerIndex: 2 },
  { id: 'q330', text: 'The most common side effect of Rifampicin is:', options: ['Optic Neuritis', 'Red color body secretion', 'Ototoxicity', 'Metallic'], answerIndex: 1 },
  { id: 'q331', text: 'What is the major role of Nepal Health Professional Council?', options: ['Regulate health service', 'Regulate Public health workers', 'Regulate the Health professionals', 'Regulate paramedical workers'], answerIndex: 2 },
];

// Export all questions - they will be randomized when starting an exam
export const sampleQuestions: Question[] = baseQuestions;
